In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
import requests as req
import json
from pprint import pprint

In [2]:
df = pd.read_csv("Raw_Data/HDI_Index_raw.csv", encoding='ISO-8859-1')

In [3]:
alias = pd.read_csv("Raw_Data/alias.csv")

In [4]:
# Set up the function for putting in country codes

def match_countries(name, alias):
    if name in alias['rw_country_name'].values:
        code = alias.loc[alias['rw_country_name'].isin([name]), 'rw_country_code'].values[0]
        return code
    else:
        print(name)
        print('not found in alias')
        code = input("Country Code? ")
        if code:
            return code
        else:
            return None

In [5]:
# Function to add ID column

def set_id_column(df):
    id_array = []
    for x in range(len(df)):
        holder = str(df.iloc[x,1]) + str(df.iloc[x,2])[2:]
        id_array.append(holder)
    
    return id_array

## HDI Index

In [ ]:
# This is the key code block. The country names from the worksheet all have a space in front,
# so they won't line up with the names in the "alias" sheet without this code.

for x in range(len(df['Country'])):
   df.iloc[x,0] = df.iloc[x,0][1:]
#print(df['Country'].values)

In [ ]:
# Apply the function to the dataset at hand

df['Ccode'] = df.apply(lambda row: match_countries(row['Country'], alias), axis=1)
df.head(20)


In [ ]:
hdi_melt = pd.melt(df, id_vars=['Country', 'Ccode'], value_vars=['1990','1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'])
hdi_melt.head(20)

In [ ]:
hdi_melt = hdi_melt.rename(columns={'Country': 'Country Name', 'Ccode':'Country Code', 'variable': 'Year', 'value':'HDI Index'})

## Add the ID_column

hdi_melt['ID_col'] = set_id_column(hdi_melt)

hdi_melt.head()
hdi_melt.to_csv("Melt_Data/HDI_Index.csv")

In [ ]:
hdi_melt = pd.read_csv("Melt_Data/HDI_Index.csv", index_col=0)
hdi_melt.head()

In [ ]:
len(hdi_melt)

## Read in Battle Deaths

In [ ]:
battle_melt = pd.read_csv("Raw_Data/BattleDeaths.csv", index_col=0)

In [ ]:
battle_melt = battle_melt[['Country Name', 'Country Code', 'Year', 'Battle Deaths']]
battle_melt.head()

In [ ]:
battle_melt['Year'] = battle_melt['Year'].astype(str)

In [ ]:
battle_melt['ID_col'] = set_id_column(battle_melt)
battle_melt.to_csv("Melt_Data/Battle_melt.csv")
battle_melt.head()

## Access to Electricity

In [ ]:
df = pd.read_csv("Raw_Data/Access_Electricity.csv", encoding='ISO-8859-1')
df.head()

In [ ]:
electric_melt = pd.melt(df, id_vars=['Country Name', 'Country Code'], value_vars=['1990','1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016'])
electric_melt = electric_melt.rename(columns={'variable': 'Year', 'value':'% Access to Electr'})
electric_melt.head()

In [ ]:
electric_melt['ID_col'] = set_id_column(electric_melt)
electric_melt.to_csv("Melt_Data/Electric_melt.csv")
electric_melt.head()

## Human Rights Protection

In [ ]:
hr_melt = pd.read_csv("Raw_Data/human_rights_protection.csv")

In [ ]:
hr_melt.head()

In [ ]:
hr_melt = hr_melt.loc[hr_melt['Year'] >= 1990,:]

In [ ]:
hr_melt = hr_melt.rename(columns={'Entity':'Country Name', 'Code':'Country Code'})
hr_melt.head()

In [ ]:
hr_melt['Year'] = hr_melt['Year'].astype(str)

In [ ]:
hr_melt['ID_col'] = set_id_column(hr_melt)
hr_melt.to_csv("Melt_Data/Human_Rights_Melt.csv")
hr_melt.head()

## Access to Water

In [ ]:
water_melt = pd.read_csv("Raw_Data/water_source.csv")

In [ ]:
water_melt.head()

In [ ]:
water_melt = water_melt.rename(columns={'Entity':'Country Name', 'Code':'Country Code'})
water_melt.head()

In [ ]:
water_melt['Year'].dtypes
water_melt['Year'] = water_melt['Year'].astype(str)

In [ ]:
water_melt['ID_col'] = set_id_column(water_melt)
water_melt.to_csv("Melt_Data/Water_Melt.csv")
water_melt.head()

## Annual GDP Growth

In [ ]:
df = pd.read_csv("Raw_Data/GDP_Growth_Data.csv", encoding='ISO-8859-1')
df.head()

In [ ]:
gdp_melt = pd.melt(df, id_vars=['Country Name', 'Country Code'], value_vars=['1990','1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'])
gdp_melt = gdp_melt.rename(columns={'variable': 'Year', 'value':'Annual GDP Growth'})
gdp_melt.head()

In [ ]:
gdp_melt['ID_col'] = set_id_column(gdp_melt)
gdp_melt.to_csv("Melt_Data/gdp_melt.csv")
gdp_melt.head()

## Population

In [ ]:
df = pd.read_csv("Raw_Data/Population_OverTime.csv", encoding='ISO-8859-1')
df.head()

In [ ]:
pop_melt = pd.melt(df, id_vars=['Country Name', 'Country Code'], value_vars=['1990','1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'])
pop_melt = pop_melt.rename(columns={'variable': 'Year', 'value':'Population'})
pop_melt.head()

In [ ]:
pop_melt['ID_col'] = set_id_column(pop_melt)
pop_melt.to_csv("Melt_Data/pop_melt.csv")
pop_melt.head()

In [6]:
# After doing some cleaning on the pop melt file (removing the 
# rows that we know are not countries). We read the file back in.

pop_melt = pd.read_csv('Melt_Data/pop_melt_cleaned.csv')
len(pop_melt)

6104

## Refugees

In [ ]:
df = pd.read_csv("Raw_Data/countries_over_time.csv")
df.head()

In [ ]:
df = df.loc[df['Type']=='Refugees',:]

In [ ]:
ref_melt = df.rename(columns={'Origin':'Country Name', 'ocode':'Country Code', 'Value':'Refugees'})
ref_melt.head()

In [ ]:
ref_melt = ref_melt[['Country Name', 'Country Code', 'Year', 'Refugees']]
ref_melt = ref_melt.loc[ref_melt['Year'] >= 1990, :]
ref_melt.head()

In [ ]:
ref_melt['ID_col'] = set_id_column(ref_melt)
ref_melt.to_csv("Melt_Data/Ref_melt.csv")
ref_melt.head()

## Merging

In [7]:
# Start with the population file as the beginning of the Base before merging

Base = pop_melt
len(Base)

6104

In [8]:
Base.head()

Country Name Country Code  Year  Population ID_col
0        Aruba          ABW  1990     62149.0  ABW90
1  Afghanistan          AFG  1990  12249114.0  AFG90
2       Angola          AGO  1990  12171441.0  AGO90
3      Albania          ALB  1990   3286542.0  ALB90
4      Andorra          AND  1990     54509.0  AND90

In [9]:
# We know there are 9 rows not covered by the Population file, and we'll using a "missing rows" csv.

df2 = pd.read_csv("Melt_Data/Missing_pop_rows.csv")

Base.append(df2, ignore_index=True)

Country Name Country Code  Year   Population ID_col
0                              Aruba          ABW  1990      62149.0  ABW90
1                        Afghanistan          AFG  1990   12249114.0  AFG90
2                             Angola          AGO  1990   12171441.0  AGO90
3                            Albania          ALB  1990    3286542.0  ALB90
4                            Andorra          AND  1990      54509.0  AND90
5               United Arab Emirates          ARE  1990    1860174.0  ARE90
6                          Argentina          ARG  1990   32729739.0  ARG90
7                            Armenia          ARM  1990    3538165.0  ARM90
8                     American Samoa          ASM  1990      47038.0  ASM90
9                Antigua and Barbuda          ATG  1990      66696.0  ATG90
10                         Australia          AUS  1990   17065100.0  AUS90
11                           Austria          AUT  1990    7677850.0  AUT90
12                        Azerbaijan          AZE  1990    7159000.0  AZE90
13                           Burundi          BDI  1990    5415415.0  BDI90
14                           Belgium          BEL  1990    9967379.0  BEL90
15                             Benin          BEN  1990    4978496.0  BEN90
16                      Burkina Faso          BFA  1990    8811034.0  BFA90
17                        Bangladesh          BGD  1990  106188642.0  BGD90
18                          Bulgaria          BGR  1990    8718289.0  BGR90
19                           Bahrain          BHR  1990     495931.0  BHR90
20                      Bahamas, The          BHS  1990     256336.0  BHS90
21            Bosnia and Herzegovina          BIH  1990    4463422.0  BIH90
22                           Belarus          BLR  1990   10189000.0  BLR90
23                            Belize          BLZ  1990     187552.0  BLZ90
24                           Bermuda          BMU  1990      59326.0  BMU90
25                           Bolivia          BOL  1990    6856244.0  BOL90
26                            Brazil          BRA  1990  149352145.0  BRA90
27                          Barbados          BRB  1990     260374.0  BRB90
28                 Brunei Darussalam          BRN  1990     258785.0  BRN90
29                            Bhutan          BTN  1990     537280.0  BTN90
...                              ...          ...   ...          ...    ...
6083                         Tunisia          TUN  2017   11532127.0  TUN17
6084                          Turkey          TUR  2017   80745020.0  TUR17
6085                          Tuvalu          TUV  2017      11192.0  TUV17
6086                        Tanzania          TZA  2017   57310019.0  TZA17
6087                          Uganda          UGA  2017   42862958.0  UGA17
6088                         Ukraine          UKR  2017   44831159.0  UKR17
6089                         Uruguay          URY  2017    3456750.0  URY17
6090                   United States          USA  2017  325719178.0  USA17
6091                      Uzbekistan          UZB  2017   32387200.0  UZB17
6092  St. Vincent and the Grenadines          VCT  2017     109897.0  VCT17
6093                   Venezuela, RB          VEN  2017   31977065.0  VEN17
6094          British Virgin Islands          VGB  2017      31196.0  VGB17
6095           Virgin Islands (U.S.)          VIR  2017     107268.0  VIR17
6096                         Vietnam          VNM  2017   95540800.0  VNM17
6097                         Vanuatu          VUT  2017     276244.0  VUT17
6098                           Samoa          WSM  2017     196440.0  WSM17
6099                          Kosovo          XKX  2017    1830700.0  XKX17
6100                     Yemen, Rep.          YEM  2017   28250420.0  YEM17
6101                    South Africa          ZAF  2017   56717156.0  ZAF17
6102                          Zambia          ZMB  2017   17094130.0  ZMB17
6103                        Zimbabwe          ZWE  2017   16529904.0  ZW

In [12]:
battle_melt = pd.read_csv("Melt_Data/Battle_melt.csv", index_col=0)

Base = Base.merge(battle_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x  Population ID_col Country Name_y  \
0          Aruba            ABW    1990     62149.0  ABW90          Aruba   
1    Afghanistan            AFG    1990  12249114.0  AFG90    Afghanistan   
2         Angola            AGO    1990  12171441.0  AGO90         Angola   
3        Albania            ALB    1990   3286542.0  ALB90        Albania   
4        Andorra            AND    1990     54509.0  AND90        Andorra   

  Country Code_y  Year_y  Battle Deaths  
0            ABW  1990.0            0.0  
1            AFG  1990.0         1478.0  
2            AGO  1990.0         2558.0  
3            ALB  1990.0            0.0  
4            AND  1990.0            0.0

In [13]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths']]
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths
0          Aruba            ABW    1990  ABW90     62149.0            0.0
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0
2         Angola            AGO    1990  AGO90  12171441.0         2558.0
3        Albania            ALB    1990  ALB90   3286542.0            0.0
4        Andorra            AND    1990  AND90     54509.0            0.0

In [15]:
electric_melt = pd.read_csv("Melt_Data/Electric_melt.csv", index_col=0)

Base = Base.merge(electric_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

  Country Name Country Code    Year  % Access to Electr  
0        Aruba          ABW  1990.0           88.445351  
1  Afghanistan          AFG  1990.0            0.010000  
2       Angola          AGO  1990.0           11.397808  
3      Albania          ALB  1990.0          100.000000  
4      Andorra          AND  1990.0          100.000000

In [16]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths', '% Access to Electr']]
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  
0           88.445351  
1            0.010000  
2           11.397808  
3          100.000000  
4          100.000000

In [18]:
hr_melt = pd.read_csv("Melt_Data/Human_Rights_Melt.csv", index_col=0)

Base = Base.merge(hr_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr Country Name Country Code    Year  HR Protect Score  
0           88.445351          NaN          NaN     NaN               NaN  
1            0.010000  Afghanistan          AFG  1990.0         -2.096220  
2           11.397808       Angola          AGO  1990.0         -1.586040  
3          100.000000      Albania          ALB  1990.0         -0.381224  
4          100.000000          NaN          NaN     NaN               NaN

In [19]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths', '% Access to Electr', 'HR Protect Score']]

Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  
0           88.445351               NaN  
1            0.010000         -2.096220  
2           11.397808         -1.586040  
3          100.000000         -0.381224  
4          100.000000               NaN

In [20]:
water_melt = pd.read_csv("Melt_Data/Water_Melt.csv", index_col=0)

Base = Base.merge(water_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score Country Name Country Code    Year  \
0           88.445351               NaN        Aruba          ABW  1990.0   
1            0.010000         -2.096220          NaN          NaN     NaN   
2           11.397808         -1.586040       Angola          AGO  1990.0   
3          100.000000         -0.381224          NaN          NaN     NaN   
4          100.000000               NaN      Andorra          AND  1990.0   

   Population without access to improved water source (people)  
0                                             5593.0            
1                                                NaN            
2                                          6609092.0            
3                                                NaN            
4                                                0.0

In [21]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths', '% Access to Electr', 'HR Protect Score', 'Population without access to improved water source (people)']]

Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  \
0           88.445351               NaN   
1            0.010000         -2.096220   
2           11.397808         -1.586040   
3          100.000000         -0.381224   
4          100.000000               NaN   

   Population without access to improved water source (people)  
0                                             5593.0            
1                                                NaN            
2                                          6609092.0            
3                                                NaN            
4                                                0.0

In [22]:
Base = Base.rename(columns={'Population without access to improved water source (people)': 'Water Access'})
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  
0           88.445351               NaN        5593.0  
1            0.010000         -2.096220           NaN  
2           11.397808         -1.586040     6609092.0  
3          100.000000         -0.381224           NaN  
4          100.000000               NaN           0.0

In [23]:
gdp_melt = pd.read_csv("Melt_Data/gdp_melt.csv", index_col=0)

Base = Base.merge(gdp_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access Country Name  \
0           88.445351               NaN        5593.0        Aruba   
1            0.010000         -2.096220           NaN  Afghanistan   
2           11.397808         -1.586040     6609092.0       Angola   
3          100.000000         -0.381224           NaN      Albania   
4          100.000000               NaN           0.0      Andorra   

  Country Code    Year  Annual GDP Growth  
0          ABW  1990.0                NaN  
1          AFG  1990.0                NaN  
2          AGO  1990.0          -3.450099  
3          ALB  1990.0          -9.575640  
4          AND  1990.0           3.781388

In [24]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths', '% Access to Electr', 'HR Protect Score', 'Water Access', 'Annual GDP Growth']]

Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  
0           88.445351               NaN        5593.0                NaN  
1            0.010000         -2.096220           NaN                NaN  
2           11.397808         -1.586040     6609092.0          -3.450099  
3          100.000000         -0.381224           NaN          -9.575640  
4          100.000000               NaN           0.0           3.781388

In [25]:
hdi_melt = pd.read_csv("Melt_Data/HDI_Index.csv", index_col=0)

Base = Base.merge(hdi_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  \
0           88.445351               NaN        5593.0                NaN   
1            0.010000         -2.096220           NaN                NaN   
2           11.397808         -1.586040     6609092.0          -3.450099   
3          100.000000         -0.381224           NaN          -9.575640   
4          100.000000               NaN           0.0           3.781388   

  Country Name Country Code    Year  HDI Index  
0          NaN          NaN     NaN        NaN  
1  Afghanistan          AFG  1990.0        NaN  
2       Angola          AGO  1990.0        NaN  
3      Albania          ALB  1990.0      0.645  
4      Andorra          AND  1990.0        NaN

In [26]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths', '% Access to Electr', 'HR Protect Score', 'Water Access', 'Annual GDP Growth', 'HDI Index']]

Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  \
0           88.445351               NaN        5593.0                NaN   
1            0.010000         -2.096220           NaN                NaN   
2           11.397808         -1.586040     6609092.0          -3.450099   
3          100.000000         -0.381224           NaN          -9.575640   
4          100.000000               NaN           0.0           3.781388   

   HDI Index  
0        NaN  
1        NaN  
2        NaN  
3      0.645  
4        NaN

In [27]:
ref_melt = pd.read_csv("Melt_Data/Ref_melt.csv", index_col=0)

Base = Base.merge(ref_melt, how='left', left_on=['ID_col'], right_on=['ID_col'])
Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  \
0           88.445351               NaN        5593.0                NaN   
1            0.010000         -2.096220           NaN                NaN   
2           11.397808         -1.586040     6609092.0          -3.450099   
3          100.000000         -0.381224           NaN          -9.575640   
4          100.000000               NaN           0.0           3.781388   

   HDI Index Country Name Country Code    Year   Refugees  
0        NaN          NaN          NaN     NaN        NaN  
1        NaN  Afghanistan          AFG  1990.0  6339095.0  
2        NaN       Angola          AGO  1990.0   407760.0  
3      0.645      Albania          ALB  1990.0     1822.0  
4        NaN          NaN          NaN     NaN        NaN

In [28]:
Base = Base[['Country Name_x', 'Country Code_x', 'Year_x', 'ID_col', 'Population', 'Battle Deaths', '% Access to Electr', 'HR Protect Score', 'Water Access', 'Annual GDP Growth', 'HDI Index', 'Refugees']]

Base.head()

Country Name_x Country Code_x  Year_x ID_col  Population  Battle Deaths  \
0          Aruba            ABW    1990  ABW90     62149.0            0.0   
1    Afghanistan            AFG    1990  AFG90  12249114.0         1478.0   
2         Angola            AGO    1990  AGO90  12171441.0         2558.0   
3        Albania            ALB    1990  ALB90   3286542.0            0.0   
4        Andorra            AND    1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  \
0           88.445351               NaN        5593.0                NaN   
1            0.010000         -2.096220           NaN                NaN   
2           11.397808         -1.586040     6609092.0          -3.450099   
3          100.000000         -0.381224           NaN          -9.575640   
4          100.000000               NaN           0.0           3.781388   

   HDI Index   Refugees  
0        NaN        NaN  
1        NaN  6339095.0  
2        NaN   407760.0  
3      0.645     1822.0  
4        NaN        NaN

In [29]:
Base = Base.rename(columns={'Country Name_x': 'Country Name', 'Country Code_x': 'Country Code', 'Year_x': 'Year'})
Base.head()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0        Aruba          ABW  1990  ABW90     62149.0            0.0   
1  Afghanistan          AFG  1990  AFG90  12249114.0         1478.0   
2       Angola          AGO  1990  AGO90  12171441.0         2558.0   
3      Albania          ALB  1990  ALB90   3286542.0            0.0   
4      Andorra          AND  1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  \
0           88.445351               NaN        5593.0                NaN   
1            0.010000         -2.096220           NaN                NaN   
2           11.397808         -1.586040     6609092.0          -3.450099   
3          100.000000         -0.381224           NaN          -9.575640   
4          100.000000               NaN           0.0           3.781388   

   HDI Index   Refugees  
0        NaN        NaN  
1        NaN  6339095.0  
2        NaN   407760.0  
3      0.645     1822.0  
4        NaN        NaN

In [30]:
Base.to_csv("Melt_Data/Full_Data_Raw_PopFirst.csv")

## Caculations and Fills

### From here, can read in CSV file and no need to repeat above steps

In [32]:
Base = pd.read_csv('Melt_Data/Full_Data_Raw_PopFirst.csv', index_col=0)

In [33]:
# Turn Water Access into a Percentage of Population, right now it is a count
Base['% Water Access'] = Base['Water Access'] / Base['Population']
Base.head()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0        Aruba          ABW  1990  ABW90     62149.0            0.0   
1  Afghanistan          AFG  1990  AFG90  12249114.0         1478.0   
2       Angola          AGO  1990  AGO90  12171441.0         2558.0   
3      Albania          ALB  1990  ALB90   3286542.0            0.0   
4      Andorra          AND  1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Water Access  Annual GDP Growth  \
0           88.445351               NaN        5593.0                NaN   
1            0.010000         -2.096220           NaN                NaN   
2           11.397808         -1.586040     6609092.0          -3.450099   
3          100.000000         -0.381224           NaN          -9.575640   
4          100.000000               NaN           0.0           3.781388   

   HDI Index   Refugees  % Water Access  
0        NaN        NaN        0.089993  
1        NaN  6339095.0             NaN  
2        NaN   407760.0        0.543000  
3      0.645     1822.0             NaN  
4        NaN        NaN        0.000000

In [34]:
del Base['Water Access']
Base.head()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0        Aruba          ABW  1990  ABW90     62149.0            0.0   
1  Afghanistan          AFG  1990  AFG90  12249114.0         1478.0   
2       Angola          AGO  1990  AGO90  12171441.0         2558.0   
3      Albania          ALB  1990  ALB90   3286542.0            0.0   
4      Andorra          AND  1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Annual GDP Growth  HDI Index  \
0           88.445351               NaN                NaN        NaN   
1            0.010000         -2.096220                NaN        NaN   
2           11.397808         -1.586040          -3.450099        NaN   
3          100.000000         -0.381224          -9.575640      0.645   
4          100.000000               NaN           3.781388        NaN   

    Refugees  % Water Access  
0        NaN        0.089993  
1  6339095.0             NaN  
2   407760.0        0.543000  
3     1822.0             NaN  
4        NaN        0.000000

In [35]:
# Function to set a column for Population at t + whatever

def set_t_plus(df, key_col_number, last_year, num_years):
    array_t = []
    failed_counter = 0
    working_counter = 0
    for x in range(len(df)):
        cell_ctr = df.iloc[x,1]
        cell_yr = df.iloc[x,2]
        try:
            if int(cell_yr) < last_year:
                new_yr = int(cell_yr)+ num_years
                new_yr_str = str(new_yr)[-2:]
                new_cell = cell_ctr + new_yr_str
                new_value = df[df['ID_col']==new_cell].iloc[0, key_col_number]
                array_t.append(new_value)
                working_counter += 1
            else:
                array_t.append(None)
                working_counter += 1
        except:
            array_t.append(None)
            failed_counter += 1
    print(f'Counter of Successful tries: {working_counter}')
    print(f'Counter of Failed tries: {failed_counter}')
            
    return array_t

In [36]:
# Make some quick changes to the 'Refugees' column and insert '% Refugees' column

Base['Refugees'] = Base['Refugees'].fillna(0)

Base['% Refugees'] = Base['Refugees'] / Base['Population']
Base.head()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0        Aruba          ABW  1990  ABW90     62149.0            0.0   
1  Afghanistan          AFG  1990  AFG90  12249114.0         1478.0   
2       Angola          AGO  1990  AGO90  12171441.0         2558.0   
3      Albania          ALB  1990  ALB90   3286542.0            0.0   
4      Andorra          AND  1990  AND90     54509.0            0.0   

   % Access to Electr  HR Protect Score  Annual GDP Growth  HDI Index  \
0           88.445351               NaN                NaN        NaN   
1            0.010000         -2.096220                NaN        NaN   
2           11.397808         -1.586040          -3.450099        NaN   
3          100.000000         -0.381224          -9.575640      0.645   
4          100.000000               NaN           3.781388        NaN   

    Refugees  % Water Access  % Refugees  
0        0.0        0.089993    0.000000  
1  6339095.0             NaN    0.517515  
2   407760.0        0.543000    0.033501  
3     1822.0             NaN    0.000554  
4        0.0        0.000000    0.000000

### Fill Blanks using with a function to run both ffill and means methods

In [37]:
# First create a list of unique country codes
all_countries = Base['Country Code'].unique()
all_countries
len(all_countries)

218

In [38]:
Base.head()
len(Base)

6104

In [39]:
# This is just to see how large the df would be if we dropped all NA
dropped = Base.dropna()
len(dropped)

3828

In [40]:
from sklearn.preprocessing import Imputer

Base2 = pd.DataFrame(columns=["Country Name", "Country Code", "Year", "ID_col", "Population", "Battle Deaths", "% Access to Electr", "HR Protect Score", "Annual GDP Growth", "HDI Index", "Refugees", "% Water Access", "% Refugees"])
col_names = ['Population', '% Access to Electr', 'HR Protect Score', 'Annual GDP Growth', 'HDI Index', '% Water Access']
   
count_unfillable = 0
did_fill = 0

for country in all_countries:
    temp_df = Base.loc[Base['Country Code']== country,:]
    temp_df = temp_df.sort_values(by='Year', ascending=True)
   
    for col in col_names:
        if (temp_df[col].isnull().sum() > 0) & (temp_df[col].isnull().sum() <= 5):
            print(country)
            print(col)
            sum_fill = temp_df[col].isnull().sum()
            did_fill += sum_fill
        
            # Below uses forward fill method
            #temp_df[col] = temp_df[col].fillna(method='ffill')
            
            # Below uses means fill method, has been commented out
            values = temp_df[col].values.reshape(-1, 1)
            imputer = Imputer(missing_values='NaN', strategy='mean')
            transformed_values = imputer.fit_transform(values)
            print(transformed_values)
            
            temp_df[col] = transformed_values
            
        elif (temp_df[col].isnull().sum() > 5):
            sum_unfiller = temp_df[col].isnull().sum()
            count_unfillable += sum_unfiller
        
    Base2 = pd.concat([Base2, temp_df])
    
print(f'Number of Column/Countries where we can backfill: {did_fill}')
print(f'Number of Column/Countries where we can\'t backfill: {count_unfillable}')

ABW
% Access to Electr
[[88.44535065]
 [88.78084564]
 [89.11582947]
 [89.44775391]
 [89.77355957]
 [90.09018707]
 [90.39458466]
 [90.68367767]
 [90.954422  ]
 [91.20375061]
 [91.660398  ]
 [91.63809204]
 [91.83371735]
 [92.0230484 ]
 [92.21216583]
 [92.40711975]
 [92.61398315]
 [92.83882141]
 [93.08616638]
 [93.35454559]
 [93.35629215]
 [93.94237518]
 [94.2558136 ]
 [94.57826233]
 [94.90672302]
 [95.23818207]
 [95.57014465]
 [92.01503008]]
ABW
% Water Access
[[0.0899934 ]
 [0.08699824]
 [0.08400381]
 [0.08100243]
 [0.0770013 ]
 [0.0740003 ]
 [0.0709976 ]
 [0.06800389]
 [0.06400312]
 [0.06099657]
 [0.05799478]
 [0.0549958 ]
 [0.0510043 ]
 [0.0480019 ]
 [0.04499833]
 [0.04199698]
 [0.03800381]
 [0.03500296]
 [0.03199708]
 [0.02899865]
 [0.02599612]
 [0.02199837]
 [0.01900036]
 [0.01900433]
 [0.01899899]
 [0.01899541]
 [0.05053803]
 [0.05053803]]
AFG
% Access to Electr
[[1.00000000e-02]
 [1.00000000e-02]
 [1.00000000e-02]
 [1.00000000e-02]
 [1.00000000e-02]
 [1.00000000e-02]
 [1.00000000e

BHS
% Water Access
[[0.02756531]
 [0.02756531]
 [0.02756531]
 [0.03699961]
 [0.03699958]
 [0.03700161]
 [0.03699919]
 [0.03700038]
 [0.03699924]
 [0.03600139]
 [0.03399913]
 [0.0329985 ]
 [0.03100043]
 [0.0299988 ]
 [0.02800084]
 [0.02700084]
 [0.02500074]
 [0.02400037]
 [0.02200037]
 [0.02100007]
 [0.01900053]
 [0.01799939]
 [0.01600101]
 [0.01600042]
 [0.01600077]
 [0.01599895]
 [0.02756531]
 [0.02756531]]
BIH
% Access to Electr
[[ 96.88565063]
 [ 97.11223602]
 [ 97.33831024]
 [ 97.56132507]
 [ 97.77822113]
 [ 97.98593903]
 [ 98.16995239]
 [ 98.34786987]
 [ 98.50772095]
 [ 98.64764404]
 [ 98.76785278]
 [ 99.4       ]
 [ 98.5       ]
 [ 99.04735565]
 [ 99.1321106 ]
 [ 99.22267914]
 [ 99.38727699]
 [ 99.7       ]
 [ 99.58003998]
 [ 99.72540283]
 [ 99.85575867]
 [ 99.70578055]
 [ 99.98661804]
 [ 99.99848938]
 [100.        ]
 [100.        ]
 [100.        ]
 [ 98.9016383 ]]
BIH
HR Protect Score
[[-0.2395803]
 [-0.2395803]
 [-2.35559  ]
 [-2.33533  ]
 [-2.16841  ]
 [-1.89159  ]
 [-1.18766 

CHN
% Access to Electr
[[ 92.21601105]
 [ 92.65581512]
 [ 93.09511566]
 [ 93.53135681]
 [ 93.96147156]
 [ 94.38241577]
 [ 94.79112244]
 [ 95.18453217]
 [ 95.5595932 ]
 [ 95.9132309 ]
 [ 96.243927  ]
 [ 96.55620575]
 [ 96.85614014]
 [ 97.1497879 ]
 [ 97.44321442]
 [ 97.74249268]
 [ 98.06681061]
 [ 98.39870453]
 [ 98.74991608]
 [ 99.11564636]
 [ 99.7       ]
 [ 99.74872589]
 [ 99.91638184]
 [ 99.98311615]
 [ 99.99848938]
 [100.        ]
 [100.        ]
 [ 96.92445272]]
CHN
HR Protect Score
[[-1.22342  ]
 [-1.01838  ]
 [-0.992801 ]
 [-0.977409 ]
 [-1.1482   ]
 [-1.14038  ]
 [-1.12575  ]
 [-1.22766  ]
 [-1.28203  ]
 [-1.27341  ]
 [-1.29477  ]
 [-1.31188  ]
 [-1.37263  ]
 [-1.39388  ]
 [-1.40746  ]
 [-1.4294   ]
 [-1.37836  ]
 [-1.31596  ]
 [-1.42417  ]
 [-1.44708  ]
 [-1.43895  ]
 [-1.40096  ]
 [-1.29196  ]
 [-1.21209  ]
 [-1.11445  ]
 [-1.2657376]
 [-1.2657376]
 [-1.2657376]]
CHN
% Water Access
[[0.331     ]
 [0.317     ]
 [0.302     ]
 [0.288     ]
 [0.275     ]
 [0.261     ]
 [0.248    

HR Protect Score
[[1.57355  ]
 [1.58847  ]
 [1.42894  ]
 [1.30527  ]
 [1.1741   ]
 [1.08554  ]
 [1.22559  ]
 [1.26899  ]
 [1.25659  ]
 [1.08894  ]
 [1.12521  ]
 [0.924873 ]
 [0.924375 ]
 [0.847651 ]
 [0.929931 ]
 [1.25512  ]
 [1.52933  ]
 [1.67071  ]
 [1.71155  ]
 [1.80427  ]
 [1.8171   ]
 [1.85783  ]
 [1.92624  ]
 [1.97088  ]
 [1.97856  ]
 [1.4107844]
 [1.4107844]
 [1.4107844]]
DEU
% Water Access
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
DJI
% Access to Electr
[[59.60907745]
 [59.36952591]
 [59.1294632 ]
 [58.88634491]
 [58.63710403]
 [58.37868881]
 [62.        ]
 [57.82208633]
 [57.51778412]
 [57.19207001]
 [56.84339905]
 [56.47632217]
 [49.7       ]
 [55.71118546]
 [55.32525635]
 [54.94516754]
 [55.5       ]
 [54.22677231]
 [53.89907837]
 [53.59241486]
 [53.30377197]
 [53.03014755]
 [54.6       ]
 [52.51594543]
 [52.26935959]
 [52.02577591]
 [51.78269196]
 [

 [100.]]
FRA
HR Protect Score
[[1.1903    ]
 [1.38264   ]
 [1.44818   ]
 [1.29026   ]
 [1.21928   ]
 [1.03719   ]
 [1.02802   ]
 [1.02369   ]
 [0.86971   ]
 [0.707112  ]
 [0.701948  ]
 [0.625554  ]
 [0.529675  ]
 [0.397417  ]
 [0.457784  ]
 [0.556992  ]
 [0.626693  ]
 [0.701749  ]
 [0.824052  ]
 [0.963078  ]
 [1.04573   ]
 [1.10715   ]
 [1.18628   ]
 [1.30073   ]
 [1.29703   ]
 [0.94072976]
 [0.94072976]
 [0.94072976]]
FRA
% Water Access
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
FRO
% Access to Electr
[[100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]]
FSM
% Access to Electr
[[28.03698158]
 [29.92145157]
 [31.80541229]
 [33.68631363]
 [35.56109619]
 [37.42670441]
 [39.28007126]
 [41.11814499

GRD
% Access to Electr
[[81.56082916]
 [82.03704834]
 [82.51274872]
 [82.98539734]
 [83.45192719]
 [83.90927887]
 [84.35438538]
 [84.78421021]
 [85.04      ]
 [85.58572388]
 [85.95281982]
 [86.30150604]
 [86.6378479 ]
 [86.96790314]
 [87.29773712]
 [87.63341522]
 [87.98100281]
 [88.34655762]
 [90.        ]
 [89.14373016]
 [89.57085419]
 [88.8       ]
 [90.46715546]
 [90.93032837]
 [91.39950562]
 [91.87168884]
 [92.34436798]
 [86.95807294]]
GRD
HR Protect Score
[[1.9466    ]
 [1.9964    ]
 [2.02833   ]
 [2.0391    ]
 [2.05789   ]
 [2.06326   ]
 [2.04633   ]
 [2.0344    ]
 [2.00785   ]
 [1.979     ]
 [1.94948   ]
 [1.91148   ]
 [1.82308   ]
 [1.71642   ]
 [1.55564   ]
 [1.40952   ]
 [1.36361   ]
 [1.33631   ]
 [1.29526   ]
 [1.241     ]
 [1.14714   ]
 [0.996246  ]
 [1.14329   ]
 [1.21262   ]
 [1.21187   ]
 [1.66048504]
 [1.66048504]
 [1.66048504]]
GRD
% Water Access
[[0.03500099]
 [0.03500114]
 [0.03500072]
 [0.03399624]
 [0.03400231]
 [0.03400329]
 [0.03399937]
 [0.03399854]
 [0.0340048

IRQ
% Access to Electr
[[ 93.48020935]
 [ 93.80567932]
 [ 94.13063812]
 [ 94.45253754]
 [ 94.76832581]
 [ 95.07492828]
 [ 95.36929321]
 [ 95.64836884]
 [ 95.90908813]
 [ 96.14839172]
 [ 96.36474609]
 [ 96.56269073]
 [ 96.74828339]
 [ 96.92759705]
 [ 97.10668945]
 [ 97.29161835]
 [ 97.62211156]
 [ 98.1       ]
 [ 97.94059753]
 [ 98.21245575]
 [ 98.48660278]
 [ 98.        ]
 [ 99.3       ]
 [ 99.37960052]
 [ 99.65541077]
 [ 99.86218262]
 [100.        ]
 [ 96.90177952]]
IRQ
HR Protect Score
[[-2.48475  ]
 [-2.56272  ]
 [-2.45934  ]
 [-2.37489  ]
 [-2.25163  ]
 [-2.19704  ]
 [-2.2773   ]
 [-2.24556  ]
 [-2.23826  ]
 [-2.26139  ]
 [-2.13991  ]
 [-2.0165   ]
 [-1.97979  ]
 [-1.95699  ]
 [-1.88264  ]
 [-1.9149   ]
 [-1.91686  ]
 [-1.89347  ]
 [-1.69215  ]
 [-1.42273  ]
 [-1.29885  ]
 [-1.2134   ]
 [-1.32718  ]
 [-1.49941  ]
 [-1.56777  ]
 [-1.9630172]
 [-1.9630172]
 [-1.9630172]]
IRQ
% Water Access
[[0.217     ]
 [0.21800001]
 [0.219     ]
 [0.22000001]
 [0.22100001]
 [0.21799998]
 [0.214    

KWT
HR Protect Score
[[-0.735952 ]
 [-0.864592 ]
 [-0.526788 ]
 [-0.366214 ]
 [-0.104164 ]
 [ 0.011171 ]
 [ 0.088516 ]
 [ 0.282312 ]
 [ 0.436757 ]
 [ 0.643119 ]
 [ 0.700925 ]
 [ 0.636469 ]
 [ 0.500738 ]
 [ 0.442059 ]
 [ 0.448516 ]
 [ 0.423767 ]
 [ 0.500347 ]
 [ 0.507151 ]
 [ 0.556158 ]
 [ 0.481008 ]
 [ 0.424002 ]
 [ 0.356759 ]
 [ 0.38982  ]
 [ 0.40962  ]
 [ 0.411241 ]
 [ 0.2421098]
 [ 0.2421098]
 [ 0.2421098]]
KWT
Annual GDP Growth
[[ 4.98180398]
 [ 4.98180398]
 [ 4.98180398]
 [33.99046707]
 [ 8.43616577]
 [ 4.85829122]
 [ 0.60512698]
 [ 2.47332525]
 [ 3.6620551 ]
 [-1.78900946]
 [ 4.69458199]
 [ 0.72902641]
 [ 3.00000001]
 [17.32000038]
 [10.7621943 ]
 [10.07595099]
 [ 7.52024923]
 [ 5.99166125]
 [ 2.47984383]
 [-7.07610262]
 [-2.36706194]
 [ 9.62843608]
 [ 6.62638808]
 [ 1.14903885]
 [ 0.50087698]
 [ 0.59301962]
 [ 3.54700509]
 [-2.86643105]]
KWT
% Water Access
[[0.00999993]
 [0.01000019]
 [0.01000002]
 [0.01000002]
 [0.01000002]
 [0.0100003 ]
 [0.00999975]
 [0.00999992]
 [0.01000026

MDG
% Access to Electr
[[ 9.57178211]
 [10.0140934 ]
 [ 9.2       ]
 [10.89463806]
 [11.32726288]
 [11.75070953]
 [12.16192055]
 [10.9       ]
 [12.93539619]
 [13.29154301]
 [13.62473679]
 [14.8       ]
 [14.24195862]
 [20.3       ]
 [14.83404636]
 [15.13582134]
 [15.44950294]
 [15.78115177]
 [16.13532257]
 [17.4       ]
 [16.90373993]
 [14.3       ]
 [17.73223686]
 [12.9       ]
 [18.59678078]
 [19.03506088]
 [22.9       ]
 [14.52287795]]
MDG
HR Protect Score
[[-0.256185  ]
 [-0.398943  ]
 [-0.351693  ]
 [-0.433817  ]
 [-0.214265  ]
 [-0.011247  ]
 [ 0.263413  ]
 [ 0.394548  ]
 [ 0.448465  ]
 [ 0.460997  ]
 [ 0.417907  ]
 [ 0.240303  ]
 [-0.106991  ]
 [ 0.125221  ]
 [ 0.177551  ]
 [ 0.080057  ]
 [ 0.03581   ]
 [-0.047928  ]
 [-0.294846  ]
 [-0.773414  ]
 [-0.764127  ]
 [-0.721246  ]
 [-0.739811  ]
 [-0.669146  ]
 [-0.633291  ]
 [-0.15090712]
 [-0.15090712]
 [-0.15090712]]
MDG
% Water Access
[[0.70499998]
 [0.696     ]
 [0.68599996]
 [0.676     ]
 [0.66800002]
 [0.66      ]
 [0.6520000

MNP
% Water Access
[[0.05999342]
 [0.05900683]
 [0.05699201]
 [0.05499783]
 [0.05400899]
 [0.0519919 ]
 [0.05100734]
 [0.04900205]
 [0.04699575]
 [0.04600398]
 [0.04399803]
 [0.04199573]
 [0.04099588]
 [0.03899321]
 [0.03799705]
 [0.03600339]
 [0.03399365]
 [0.03300119]
 [0.03099371]
 [0.02900815]
 [0.02800235]
 [0.02599189]
 [0.02500093]
 [0.02500185]
 [0.02500551]
 [0.0249927 ]
 [0.04042213]
 [0.04042213]]
MOZ
% Access to Electr
[[1.00000000e-02]
 [1.02698120e-02]
 [2.98860740e-02]
 [1.59723803e-01]
 [5.59485316e-01]
 [1.17910111e+00]
 [2.31869793e+00]
 [6.60000000e+00]
 [4.54894590e+00]
 [5.63347864e+00]
 [6.69505882e+00]
 [5.70000000e+00]
 [8.76905346e+00]
 [8.10000000e+00]
 [1.08179121e+01]
 [1.18480740e+01]
 [1.28901415e+01]
 [1.39501772e+01]
 [1.35712239e+01]
 [1.50000000e+01]
 [1.72579231e+01]
 [2.02000000e+01]
 [1.95431919e+01]
 [2.07008457e+01]
 [2.18645077e+01]
 [2.40000000e+01]
 [2.41983395e+01]
 [1.02280014e+01]]
MOZ
HR Protect Score
[[-1.15172   ]
 [-1.15393   ]
 [-1.1888

NGA
% Water Access
[[0.601     ]
 [0.588     ]
 [0.576     ]
 [0.564     ]
 [0.552     ]
 [0.54      ]
 [0.528     ]
 [0.517     ]
 [0.505     ]
 [0.494     ]
 [0.482     ]
 [0.47      ]
 [0.458     ]
 [0.446     ]
 [0.434     ]
 [0.422     ]
 [0.41      ]
 [0.399     ]
 [0.388     ]
 [0.377     ]
 [0.366     ]
 [0.355     ]
 [0.345     ]
 [0.334     ]
 [0.324     ]
 [0.315     ]
 [0.45346154]
 [0.45346154]]
NIC
% Access to Electr
[[66.82804108]
 [67.46522522]
 [68.10189819]
 [72.064174  ]
 [69.36301422]
 [69.98133087]
 [70.5874176 ]
 [71.17819977]
 [69.047103  ]
 [72.30165863]
 [72.82972717]
 [72.22158   ]
 [73.83669281]
 [74.32772064]
 [74.81852722]
 [73.821815  ]
 [75.82373047]
 [76.35025024]
 [76.89929199]
 [77.916313  ]
 [78.05745697]
 [78.66056824]
 [79.2756958 ]
 [79.89984131]
 [81.853073  ]
 [81.16313934]
 [81.79679871]
 [74.31371424]]
NIC
HR Protect Score
[[-0.907288  ]
 [-0.942713  ]
 [-0.880211  ]
 [-0.774019  ]
 [-0.684561  ]
 [-0.542516  ]
 [-0.436437  ]
 [-0.305773  ]
 [-

PHL
% Access to Electr
[[62.11444855]
 [63.28618622]
 [64.45741272]
 [65.4       ]
 [66.7876358 ]
 [67.94051361]
 [69.08114624]
 [70.20648956]
 [71.3       ]
 [71.87417093]
 [73.46167755]
 [74.50588989]
 [75.53775024]
 [76.6       ]
 [77.58869171]
 [78.61989594]
 [79.66300201]
 [80.72408295]
 [83.3       ]
 [82.91230011]
 [84.03495026]
 [85.17262268]
 [86.32230377]
 [87.5       ]
 [88.64569855]
 [89.08      ]
 [90.98161316]
 [76.55920305]]
PHL
HR Protect Score
[[-1.48785  ]
 [-1.48241  ]
 [-1.42243  ]
 [-1.29096  ]
 [-1.18164  ]
 [-1.2115   ]
 [-1.07966  ]
 [-1.03156  ]
 [-1.02635  ]
 [-1.19536  ]
 [-1.39653  ]
 [-1.29895  ]
 [-1.23375  ]
 [-1.37595  ]
 [-1.48604  ]
 [-1.55411  ]
 [-1.60313  ]
 [-1.58488  ]
 [-1.56442  ]
 [-1.54517  ]
 [-1.50698  ]
 [-1.38562  ]
 [-1.28572  ]
 [-1.20064  ]
 [-1.10937  ]
 [-1.3416392]
 [-1.3416392]
 [-1.3416392]]
PHL
% Water Access
[[0.161     ]
 [0.15800001]
 [0.15499999]
 [0.151     ]
 [0.148     ]
 [0.145     ]
 [0.142     ]
 [0.139     ]
 [0.1360000

 [100.]]
RUS
HR Protect Score
[[-0.522094  ]
 [-0.810421  ]
 [-0.72589   ]
 [-0.800851  ]
 [-1.25167   ]
 [-1.61927   ]
 [-1.55053   ]
 [-1.48197   ]
 [-1.62329   ]
 [-1.66419   ]
 [-1.71971   ]
 [-1.6915    ]
 [-1.59029   ]
 [-1.58319   ]
 [-1.56723   ]
 [-1.50725   ]
 [-1.47356   ]
 [-1.48179   ]
 [-1.42279   ]
 [-1.45005   ]
 [-1.37863   ]
 [-1.36868   ]
 [-1.24634   ]
 [-1.13769   ]
 [-1.06286   ]
 [-1.34926944]
 [-1.34926944]
 [-1.34926944]]
RUS
% Water Access
[[0.066     ]
 [0.064     ]
 [0.063     ]
 [0.061     ]
 [0.06      ]
 [0.058     ]
 [0.057     ]
 [0.056     ]
 [0.054     ]
 [0.053     ]
 [0.051     ]
 [0.05      ]
 [0.048     ]
 [0.047     ]
 [0.045     ]
 [0.044     ]
 [0.042     ]
 [0.041     ]
 [0.039     ]
 [0.038     ]
 [0.037     ]
 [0.035     ]
 [0.034     ]
 [0.032     ]
 [0.031     ]
 [0.031     ]
 [0.04757692]
 [0.04757692]]
RWA
% Access to Electr
[[1.00000000e-02]
 [1.00000000e-02]
 [2.30000000e+00]
 [4.27722000e-02]
 [1.88256279e-01]
 [5.77478111e-01]
 [1.16

SUR
% Access to Electr
[[100.        ]
 [100.        ]
 [100.        ]
 [100.        ]
 [ 99.99056244]
 [ 99.92409515]
 [ 99.71331787]
 [ 99.30543518]
 [ 98.74053955]
 [ 99.62406   ]
 [ 97.44142914]
 [ 96.74906921]
 [ 96.04437256]
 [ 95.33338928]
 [ 94.62218475]
 [ 93.91681671]
 [ 91.01983989]
 [ 92.54787445]
 [ 91.89490509]
 [ 91.26296234]
 [ 91.19751586]
 [ 90.05014801]
 [ 89.46326447]
 [ 88.88539124]
 [ 88.31352997]
 [ 87.74467468]
 [ 87.17631531]
 [ 94.85043308]]
SUR
HR Protect Score
[[-0.128145 ]
 [ 0.151658 ]
 [ 0.376037 ]
 [ 0.432935 ]
 [ 0.498554 ]
 [ 0.610865 ]
 [ 0.738851 ]
 [ 0.771921 ]
 [ 0.888783 ]
 [ 0.841975 ]
 [ 0.617595 ]
 [ 0.469073 ]
 [ 0.496577 ]
 [ 0.554986 ]
 [ 0.430561 ]
 [ 0.44613  ]
 [ 0.44829  ]
 [ 0.525526 ]
 [ 0.695904 ]
 [ 0.734269 ]
 [ 0.651683 ]
 [ 0.575374 ]
 [ 0.629902 ]
 [ 0.576978 ]
 [ 0.574688 ]
 [ 0.5444388]
 [ 0.5444388]
 [ 0.5444388]]
SVK
% Access to Electr
[[100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [1

TJK
% Access to Electr
[[ 96.6034317 ]
 [ 96.82150269]
 [ 97.0390625 ]
 [ 97.25356293]
 [ 97.46195221]
 [ 97.6611557 ]
 [ 97.84812164]
 [ 98.00605774]
 [ 98.15739441]
 [ 97.        ]
 [ 98.46774194]
 [ 98.49528503]
 [ 99.        ]
 [100.        ]
 [ 98.73070526]
 [ 99.3       ]
 [ 98.90644836]
 [ 99.01660919]
 [ 99.14608002]
 [ 99.        ]
 [ 99.46128082]
 [ 99.63639069]
 [ 99.1       ]
 [ 99.91744995]
 [ 99.97840881]
 [ 99.9973526 ]
 [100.        ]
 [ 98.5928146 ]]
TJK
HR Protect Score
[[-0.69294575]
 [-1.32484   ]
 [-1.55331   ]
 [-1.62114   ]
 [-1.46723   ]
 [-1.28058   ]
 [-1.19128   ]
 [-1.05257   ]
 [-0.998254  ]
 [-0.842828  ]
 [-0.701013  ]
 [-0.492311  ]
 [-0.365753  ]
 [-0.253981  ]
 [-0.274121  ]
 [-0.368434  ]
 [-0.435455  ]
 [-0.411751  ]
 [-0.286316  ]
 [-0.148139  ]
 [-0.134241  ]
 [-0.245041  ]
 [-0.378916  ]
 [-0.408912  ]
 [-0.394282  ]
 [-0.69294575]
 [-0.69294575]
 [-0.69294575]]
TJK
% Water Access
[[0.35734784]
 [0.35734784]
 [0.35734784]
 [0.41800006]
 [0.4209999

% Access to Electr
[[100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]]
USA
HR Protect Score
[[ 1.43773   ]
 [ 1.25329   ]
 [ 1.20619   ]
 [ 1.28859   ]
 [ 1.31272   ]
 [ 1.28412   ]
 [ 1.24974   ]
 [ 1.19609   ]
 [ 1.12588   ]
 [ 1.01675   ]
 [ 0.828106  ]
 [ 0.518297  ]
 [ 0.308952  ]
 [ 0.087547  ]
 [-0.243617  ]
 [-0.366195  ]
 [-0.362788  ]
 [-0.295633  ]
 [-0.23465   ]
 [-0.231353  ]
 [-0.193752  ]
 [-0.194516  ]
 [-0.2285    ]
 [-0.211881  ]
 [-0.195931  ]
 [ 0.45420744]
 [ 0.45420744]
 [ 0.45420744]]
USA
% Water Access
[[0.016     ]
 [0.016     ]
 [0.015     ]
 [0.015     ]
 [0.014     ]
 [0.014     ]
 [0.013     ]
 [0.013     ]
 [0.013     ]
 [0.012     ]
 [0.012     ]
 [0.012     ]
 [0.011     ]
 [0.011     ]
 [0.011     ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.01      ]
 [0.009     ]
 [0.00900029]
 

YEM
HR Protect Score
[[-0.450716  ]
 [-0.598622  ]
 [-0.733314  ]
 [-0.825335  ]
 [-0.953344  ]
 [-0.814896  ]
 [-0.777198  ]
 [-0.835427  ]
 [-0.749836  ]
 [-0.636554  ]
 [-0.726255  ]
 [-0.771526  ]
 [-0.707975  ]
 [-0.865365  ]
 [-1.02517   ]
 [-0.963919  ]
 [-0.896904  ]
 [-1.05239   ]
 [-1.21392   ]
 [-1.35268   ]
 [-1.47154   ]
 [-1.43501   ]
 [-1.20759   ]
 [-1.11202   ]
 [-1.04155   ]
 [-0.92876224]
 [-0.92876224]
 [-0.92876224]]
YEM
Annual GDP Growth
[[  0.85871752]
 [  6.29349385]
 [  8.20759814]
 [  4.00196638]
 [  6.72194912]
 [  5.66937132]
 [  4.63496732]
 [  5.23111204]
 [  6.0066946 ]
 [  3.7755305 ]
 [  6.18191559]
 [  3.80364587]
 [  3.9352315 ]
 [  3.74739819]
 [  3.9726964 ]
 [  5.59174808]
 [  3.17040936]
 [  3.33842796]
 [  3.64756947]
 [  3.86622952]
 [  7.70230704]
 [-12.7148969 ]
 [  2.39297235]
 [  4.82341498]
 [ -0.18859145]
 [-37.14675128]
 [-34.33975436]
 [  0.85871752]]
YEM
% Water Access
[[0.33699999]
 [0.34300003]
 [0.34899996]
 [0.35500001]
 [0.36100002

In [41]:
Base2.head()
len(Base2)

6104

In [42]:
Base2 = Base2[['Country Name', 'Country Code', 'Year', 'ID_col',
              'Population', 'Battle Deaths', '% Access to Electr',
              'HR Protect Score', 'Annual GDP Growth', 'HDI Index',
              '% Water Access', 'Refugees', '% Refugees']]
Base2.tail()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
5231     Zimbabwe          ZWE  2013  ZWE13  15054506.0            0.0   
5449     Zimbabwe          ZWE  2014  ZWE14  15411675.0            0.0   
5667     Zimbabwe          ZWE  2015  ZWE15  15777451.0            0.0   
5885     Zimbabwe          ZWE  2016  ZWE16  16150362.0            0.0   
6103     Zimbabwe          ZWE  2017  ZWE17  16529904.0            0.0   

      % Access to Electr  HR Protect Score  Annual GDP Growth  HDI Index  \
5231           37.076813         -0.801210           5.529787      0.516   
5449           32.300000         -0.763910           2.127084      0.525   
5667           33.700000         -0.705892           1.689595      0.529   
5885           38.145138         -0.705892           0.615714      0.532   
6103           34.253765         -0.705892           3.447095      0.535   

      % Water Access  Refugees  % Refugees  
5231        0.227000   19734.0    0.001311  
5449        0.229000   22492.0    0.001459  
5667        0.231000   21344.0    0.001353  
5885        0.212423   18156.0    0.001124  
6103        0.212423   17390.0    0.001052

In [43]:
# Imputed Base Dataframe
Base2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 0 to 6103
Data columns (total 13 columns):
Country Name          6104 non-null object
Country Code          6104 non-null object
Year                  6104 non-null object
ID_col                6104 non-null object
Population            6090 non-null float64
Battle Deaths         6076 non-null float64
% Access to Electr    5927 non-null float64
HR Protect Score      5263 non-null float64
Annual GDP Growth     5417 non-null float64
HDI Index             4753 non-null float64
% Water Access        5398 non-null float64
Refugees              6104 non-null float64
% Refugees            6087 non-null float64
dtypes: float64(9), object(4)
memory usage: 667.6+ KB


In [44]:
dropped_new = Base2.dropna()
len(dropped_new)

4356

## We can start from here to create new models (if we keep ffill or means), 
### Just drop all the t values (for years ahead), reset according to the final year and the t number
### Save to CSV to be input into the Model

In [45]:
Base2.head()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0          Aruba          ABW  1990  ABW90     62149.0            0.0   
218        Aruba          ABW  1991  ABW91     64622.0            0.0   
436        Aruba          ABW  1992  ABW92     68235.0            0.0   
654        Aruba          ABW  1993  ABW93     72504.0            0.0   
872        Aruba          ABW  1994  ABW94     76700.0            0.0   

     % Access to Electr  HR Protect Score  Annual GDP Growth  HDI Index  \
0             88.445351               NaN                NaN        NaN   
218           88.780846               NaN                NaN        NaN   
436           89.115829               NaN                NaN        NaN   
654           89.447754               NaN                NaN        NaN   
872           89.773560               NaN                NaN        NaN   

     % Water Access  Refugees  % Refugees  
0          0.089993       0.0         0.0  
218        0.086998       0.0         0.0  
436        0.084004       0.0         0.0  
654        0.081002       0.0         0.0  
872        0.077001       0.0         0.0

In [48]:
# *** DON'T NEED TO RUN THIS BLOCK THE FIRST TIME THROUGH ***

# We are going to chop off Pop_t6, Ref_t6, % Refuggees_t6 and Change % Ref, then we'll re-add
del Base2['Pop_t']
del Base2['Ref_t']
del Base2['% Refugees_t']          
del Base2['Change % Ref']

In [49]:
Base2.head()

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0          Aruba          ABW  1990  ABW90     62149.0            0.0   
218        Aruba          ABW  1991  ABW91     64622.0            0.0   
436        Aruba          ABW  1992  ABW92     68235.0            0.0   
654        Aruba          ABW  1993  ABW93     72504.0            0.0   
872        Aruba          ABW  1994  ABW94     76700.0            0.0   

     % Access to Electr  HR Protect Score  Annual GDP Growth  HDI Index  \
0             88.445351               NaN                NaN        NaN   
218           88.780846               NaN                NaN        NaN   
436           89.115829               NaN                NaN        NaN   
654           89.447754               NaN                NaN        NaN   
872           89.773560               NaN                NaN        NaN   

     % Water Access  Refugees  % Refugees  
0          0.089993       0.0         0.0  
218        0.086998       0.0         0.0  
436        0.084004       0.0         0.0  
654        0.081002       0.0         0.0  
872        0.077001       0.0         0.0

In [50]:
#Base2['% Refugees'] = Base2['Refugees'] / Base2['Population']

Base2['Pop_t'] = set_t_plus(Base2, 4, 2010, 6)
Base2['Ref_t'] = set_t_plus(Base2, 11, 2010, 6)
Base2['% Refugees_t'] = Base2['Ref_t'] / Base2['Pop_t']
Base2['Change % Ref'] = Base2['% Refugees_t'] - Base2['% Refugees']

Counter of Successful tries: 6084
Counter of Failed tries: 20
Counter of Successful tries: 6084
Counter of Failed tries: 20


In [51]:
for_csv = Base2

In [52]:
drop_for_csv = Base2.dropna()
len(drop_for_csv)

2985

In [54]:
for_csv.head(30)

Country Name Country Code  Year ID_col  Population  Battle Deaths  \
0           Aruba          ABW  1990  ABW90     62149.0            0.0   
218         Aruba          ABW  1991  ABW91     64622.0            0.0   
436         Aruba          ABW  1992  ABW92     68235.0            0.0   
654         Aruba          ABW  1993  ABW93     72504.0            0.0   
872         Aruba          ABW  1994  ABW94     76700.0            0.0   
1090        Aruba          ABW  1995  ABW95     80324.0            0.0   
1308        Aruba          ABW  1996  ABW96     83200.0            0.0   
1526        Aruba          ABW  1997  ABW97     85451.0            0.0   
1744        Aruba          ABW  1998  ABW98     87277.0            0.0   
1962        Aruba          ABW  1999  ABW99     89005.0            0.0   
2180        Aruba          ABW  2000  ABW00     90853.0            0.0   
2398        Aruba          ABW  2001  ABW01     92898.0            0.0   
2616        Aruba          ABW  2002  ABW02     94992.0            0.0   
2834        Aruba          ABW  2003  ABW03     97017.0            0.0   
3052        Aruba          ABW  2004  ABW04     98737.0            0.0   
3270        Aruba          ABW  2005  ABW05    100031.0            0.0   
3488        Aruba          ABW  2006  ABW06    100832.0            0.0   
3706        Aruba          ABW  2007  ABW07    101220.0            0.0   
3924        Aruba          ABW  2008  ABW08    101353.0            0.0   
4142        Aruba          ABW  2009  ABW09    101453.0            0.0   
4360        Aruba          ABW  2010  ABW10    101669.0            0.0   
4578        Aruba          ABW  2011  ABW11    102053.0            0.0   
4796        Aruba          ABW  2012  ABW12    102577.0            0.0   
5014        Aruba          ABW  2013  ABW13    103187.0            0.0   
5232        Aruba          ABW  2014  ABW14    103795.0            0.0   
5450        Aruba          ABW  2015  ABW15    104341.0            0.0   
5668        Aruba          ABW  2016  ABW16    104822.0            0.0   
5886        Aruba          ABW  2017  ABW17    105264.0            0.0   
1     Afghanistan          AFG  1990  AFG90  12249114.0         1478.0   
219   Afghanistan          AFG  1991  AFG91  12993657.0         3302.0   

      % Access to Electr  HR Protect Score  Annual GDP Growth  HDI Index  \
0              88.445351               NaN                NaN        NaN   
218            88.780846               NaN                NaN        NaN   
436            89.115829               NaN                NaN        NaN   
654            89.447754               NaN                NaN        NaN   
872            89.773560               NaN                NaN        NaN   
1090           90.090187               NaN           1.245086        NaN   
1308           90.394585               NaN           7.814432        NaN   
1526           90.683678               NaN           6.666622        NaN   
1744           90.954422               NaN           1.154469        NaN   
1962           91.203751               NaN           4.514062        NaN   
2180           91.660398               NaN          -0.364696        NaN   
2398           91.638092               NaN          -2.164459        NaN   
2616           91.833717               NaN           0.465290        NaN   
2834           92.023048               NaN           7.519472        NaN   
3052           92.212166               NaN           1.176690        NaN   
3270           92.407120               NaN           0.380391        NaN   
3488           92.613983               NaN           2.355119        NaN   
3706           92.838821               NaN          -3.654626        NaN   
3924           93.086166               NaN          -6.881302        NaN   
4142           93.354546               NaN          -5.653502        NaN   
4360           93.356292               NaN                NaN        NaN   
4578           93.942375              

In [55]:
# We can re-run from the code break above, using different parameters
# with the "set_t_plus" function, then create new csv files, saved below
# to be used with the machine learning notebook.

for_csv.to_csv("ML_Datasets/ML_file_means_t6_2009.csv")